app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='home'),
    path('index.html', views.main, name='home'),
    path('portfolio.html', views.portfolio, name='portfolio'),
    path('contact.html', views.contact, name='contact'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("app.urls")),
    path("admin/", admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.


class contact(models.Model):
	name = models.CharField(
		max_length=255, verbose_name="Имя"
	)
	email = models.EmailField(
		max_length=255, verbose_name="Электронная почта"
	)
	message = models.CharField(
		max_length=2000, verbose_name="Сообщение"
	)

	def __str__(self):
		return self.name

app/forms.py
from django import forms
from .models import *


class AddForm(forms.ModelForm):
	class Meta:
		model = contact
		fields = "__all__"

app/views.py
from django.shortcuts import render

from app.forms import AddForm


def main(request):
    return render(request, 'index.html')


def portfolio(request):
    return render(request, 'portfolio.html')


def contact(request):
    form = AddForm()
    return render(request, 'contact.html', {'form': form})

app/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArmenDev</title>
    <link rel="stylesheet" href="../static/main/css/fontawesome/css/all.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>ArmenDev</h1>
            <nav>
                <ul>
                    <li><a href="index.html">Главная</a></li>
                    <li><a href="portfolio.html">Портфолио</a></li>
                    <li><a href="contact.html">Связь</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <section class="contact">
            <div class="podpis">
                <h2>Связаться с нами</h2>
                <p>Мы всегда готовы помочь вам в реализации вашего проекта.</p>
                <form id="contact" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Имя</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Электронная почта</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="id_message">Сообщение</label>
                        {{ form.message }}
                    </div>
                    <button type="submit">Отправить</button>
                </form>
            </div>
        </section>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Подготовил Артур Аветисян. Все права защищены. Все услуги и портфолио вымышлены</p>
        </div>
    </footer>
</body>
</html>

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArmenDev</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>ArmenDev</h1>
            <nav>
                <ul>
                    <li><a href="index.html">Главная</a></li>
                    <li><a href="portfolio.html">Портфолио</a></li>
                    <li><a href="contact.html">Связь</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <section class="intro">
            <div class="container">
                <h2>Мы создаем профессиональные сайты и Telegram ботов под ваши нужды</h2>
            </div>
            <div class="podpis">
                <p>Сделаем вам удобный и современный сайт, а также настроим Телеграм-бота, который облегчит вам жизнь.</p>
            </div>
        </section>

        <section class="services">
            <div class="container">
                <h2>Наши Услуги</h2>
                <div class="service-card">
                    <h3 class="default-text">Разработка Сайтов</h3>
                    <h3 class="hover-text">Создание современных и адаптивных сайтов.</h3>
                </div>
                <div class="service-card">
                    <h3 class="default-text">Телеграм Бот</h3>
                    <h3 class="hover-text">Разработка удобных Телеграм ботов для автоматизации процессов и улучшения взаимодействия с клиентами.</h3>
                </div>
                <div class="service-card">
                    <h3 class="default-text">Десктоп приложение</h3>
                    <h3 class="hover-text">Создание приложений для Windows/MacOS/Linux.</h3>
                </div>
                <div class="service-card">
                    <h3 class="default-text">Мобильное приложение</h3>
                    <h3 class="hover-text">Создание приложений для iOS/android.</h3>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Подготовил Артур Аветисян. Все права защищены. Все услуги и портфолио вымышлены</p>
        </div>
    </footer>
</body>
</html>

app/templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ArmenDev</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <header>
        <div class="container">
            <h1>ArmenDev</h1>
            <nav>
                <ul>
                    <li><a href="index.html">Главная</a></li>
                    <li><a href="portfolio.html">Портфолио</a></li>
                    <li><a href="contact.html">Связь</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main>
        <section class="portfolio">
            <div class="container">
                <h2>Наши Работы</h2>
                <div class="portfolio-item">
                    <h3 class="default-text">Бизнес помощник</h3>
                    <h3 class="hover-text">Бот-счетчик отчетов по заказам с подсчетом зарплаты.</h3>
                </div>
                <div class="portfolio-item">
                    <h3 class="default-text">Бот службы поддержки</h3>
                    <h3 class="hover-text">Разработка бота для автоматизации взаимодействия с клиентами и оперативного ответа на вопросы.</h3>
                </div>
                <div class="portfolio-item">
                    <h3 class="default-text">Телеграм магазин одежды</h3>
                    <h3 class="hover-text">Бот с встроенной логистикой, системой доставки и платежной системой.</h3>
                </div>
                <h2>В процессе</h2>
                <div class="portfolio-item">
                    <h3 class="default-text">Мобильное приложение для работников ресторана X</h3>
                    <h3 class="hover-text">Приложение для телефона, которое облегчает жизнь официантам и администраторам зала X ресторана</h3>
                </div>
                <div class="portfolio-item">
                    <h3 class="default-text">Сайт для управления VPS</h3>
                    <h3 class="hover-text">Разрабатывается сайт для облегчения в управлении удаленным сервером.</h3>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Подготовил Артур Аветисян. Все права защищены. Все услуги и портфолио вымышлены</p>
        </div>
    </footer>
</body>
</html>